### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by KrunalKharat02** [KrunalKharat02/beginner-projects#3]
update and make it more clear readme file so beginner an understand

**Comment by proffapt** [comment]
Won't be counted in hacktoberfest unless until you see #8

**Comment by Gola-k** [comment]
Assign this to me @KrunalKharat02

**Comment by rajutkarsh07** [comment]
What I have to add in the readme file

**Comment by raelimasina** [comment]
Apologies, I didn't see this issue until after I submitted a PR with an updated README. I also tried to include #8 in the PR
