### ISSUE TITLE
Add `hacktoberfest` tag to this repository

### ISSUE THREAD

**Issue by proffapt** [KrunalKharat02/beginner-projects#8]
In order to make this repository eligible in hacktoberfest, you need to add a tag "hacktoberfest" to this repository.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/86282911/194031034-57bbf3db-a2c5-468c-9391-85ed408c0f53.png">
You just have to click on that gear icon and then type 'hacktoberfest' in the Topics the choose ok/apply/done.

**Comment by proffapt** [comment]
check out the tags in this repository..

https://github.com/proffapt/code-runner

**Comment by proffapt** [comment]
@KrunalKharat02 .... you can also add the label `hacktoberfest-accepted` in the PR or MR.

**Comment by KrunalKharat02** [comment]
THANKS IT IS RESOLVED NOW

**Comment by proffapt** [comment]
Ok, since it is solved I am closing it
